#!/usr/bin/env bash
set -euo pipefail
cd $(dirname "$0")

(
  cat preamble.md
  echo
  cd ../../../build
  janet -i docs.jimage $(git rev-parse HEAD)
) | pandoc --from markdown-auto_identifiers --to html --wrap=preserve
