#!/usr/bin/env bash
set -euo pipefail
cd $(dirname "$0")

player_iife=$1
player_cjs=$2
player_esm=$3

compiler_iife=$4
compiler_cjs=$5
compiler_esm=$6

(
  cat preamble.md
  echo
  (cd ../../../build && janet -i docs.jimage $(git rev-parse HEAD))
  echo
  sed appendices.md \
    -e "s|PLACEHOLDER_PLAYER_IIFE|$player_iife|g" \
    -e "s|PLACEHOLDER_PLAYER_CJS|$player_cjs|g" \
    -e "s|PLACEHOLDER_PLAYER_ESM|$player_esm|g" \
    -e "s|PLACEHOLDER_COMPILER_IIFE|$compiler_iife|g" \
    -e "s|PLACEHOLDER_COMPILER_CJS|$compiler_cjs|g" \
    -e "s|PLACEHOLDER_COMPILER_ESM|$compiler_esm|g"
) | pandoc --from markdown-auto_identifiers --to html --wrap=preserve
