(import ../glslisp/src/index :as glslisp)
(import ../glslisp/src/type)
(import ../glslisp/src/variable)
(def p (variable/new 'p type/vec3))
(def t (variable/new 't type/float))
(def P (variable/new 'P type/vec3))
(def camera (variable/new 'camera_origin type/vec3))
(def normal (variable/new 'normal type/vec3))
(def occlusion (variable/new 'occlusion type/float))
(def lights (variable/new 'lights))
