#!/usr/bin/env bash
set -euo pipefail
cd $(dirname "$0")

printf '%s' '<header><a class="title" href="/">Bauble</a><span class="spacer"></span><a class="text-link" href="/about">About</a><a class="image-link" target="_blank" href="https://github.com/ianthehenry/bauble"><svg><use xlink:href="/icons.svg#github"/></svg></a></header>'
