#!/usr/bin/env bash
set -euo pipefail
cd $(dirname "$0")

cat <<EOF
<main>
  <p>Oh uhh hi. There aren't really docs yet but one day there will be docs here.<p>
  <p>In the meantime, uhh...<p>
  <p>This is a sphere.<p>
  <div class="bauble-placeholder">(sphere 50)</div>
  <p>This is a box.<p>
  <div class="bauble-placeholder">(box 50)</div>
  <p>Happy?<p>
</main>
EOF
