#!/usr/bin/env bash
set -euo pipefail
cd $(dirname "$0")

css=$1
js=$2

printf '<head>'
printf '<meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0">'
printf '<title>Bauble</title>'
printf '<link rel="icon" type="image/png" href="/favicon.png" />'

for file in $css; do
printf '<link rel="stylesheet" href="%s" />' "$file"
done

for file in $js; do
  printf '<script defer type="text/javascript" src="%s"></script>' "$file"
done

echo '</head>'
